# Define the default target 'all' (can be any target name)
all: my_penn-sh

my_penn-sh: my_penn-sh.c my_tokenizer.c my_redirection.c my_pipeline.c
	gcc -o my_penn-sh my_penn-sh.c my_tokenizer.c my_redirection.c my_pipeline.c -lm

clean:
	rm -f my_penn-sh
